title: hexplorer
description: Let's explore HEX. This website made with Tailwind and Jekyll.

sass:
  sass_dir: /assets/css/_sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
